<?php
/**
 * Application.php - Global Application State Manager
 *
 * Provides safe access to application-wide variables with proper error handling.
 * Replaces direct access to $GLOBALS['Application'] array which can cause
 * "Undefined array key" warnings.
 *
 * Usage:
 *   - Reading:  Application::get('cma_ip_protect', false) - second parameter is optional
 *   - Writing:  Application::set('cma_ip_protect', true)
 *   - Checking: Application::has('cma_ip_protect')
 *
 * Generated by ASP to PHP Converter
 * https://github.com/anthropics/claude-code
 */

namespace App\Library;

class Application
{
    /**
     * @var bool|null Whether to log get/set operations
     */
    private static $logEnabled = null;

    /**
     * @var int Counter for get operations
     */
    private static $getCount = 0;

    /**
     * @var int Counter for set operations
     */
    private static $setCount = 0;

    /**
     * Get an application variable with optional default value
     *
     * @param string $key The variable name
     * @param mixed $default Default value if key doesn't exist (default: '')
     * @return mixed The value or default
     */
    public static function get(string $key, $default = '')
    {
        // Initialize Application array if it doesn't exist
        if (!isset($GLOBALS['Application'])) {
            $GLOBALS['Application'] = [];
        }

        // Convert key to lowercase for case-insensitive access
        $key_lower = strtolower($key);

        // Return value if exists, otherwise return default
        $value = $GLOBALS['Application'][$key_lower] ?? $default;

        // Log the access
        self::$getCount++;
        self::logAccess('GET', $key, $value, isset($GLOBALS['Application'][$key_lower]));

        return $value;
    }

    /**
     * Set an application variable
     *
     * @param string $key The variable name
     * @param mixed $value The value to set
     * @return void
     */
    public static function set(string $key, $value): void
    {
        // Initialize Application array if it doesn't exist
        if (!isset($GLOBALS['Application'])) {
            $GLOBALS['Application'] = [];
        }

        // Convert key to lowercase for case-insensitive access
        $key_lower = strtolower($key);

        $GLOBALS['Application'][$key_lower] = $value;

        // Log the set operation
        self::$setCount++;
        self::logAccess('SET', $key, $value, true);
    }

    /**
     * Check if an application variable exists
     *
     * @param string $key The variable name
     * @return bool True if exists, false otherwise
     */
    public static function has(string $key): bool
    {
        // Initialize Application array if it doesn't exist
        if (!isset($GLOBALS['Application'])) {
            $GLOBALS['Application'] = [];
        }

        // Convert key to lowercase for case-insensitive access 
        $key_lower = strtolower($key);

        return isset($GLOBALS['Application'][$key_lower]);
    }

    /**
     * Remove an application variable
     *
     * @param string $key The variable name
     * @return void
     */
    public static function remove(string $key): void
    {
        if (!isset($GLOBALS['Application'])) {
            return;
        }

        // Convert key to lowercase for case-insensitive access 
        $key_lower = strtolower($key);

        unset($GLOBALS['Application'][$key_lower]);
    }

    /**
     * Get all application variables
     *
     * @return array All application variables
     */
    public static function all(): array
    {
        return $GLOBALS['Application'] ?? [];
    }

    /**
     * Get all application variables (alias for all())
     *
     * @return array All application variables
     */
    public static function getAll(): array
    {
        return self::all();
    }

    /**
     * Clear all application variables
     *
     * @return void
     */
    public static function clear(): void
    {
        $GLOBALS['Application'] = [];
    }

    /**
     * Log an access operation
     *
     * @param string $operation GET or SET
     * @param string $key The key being accessed
     * @param mixed $value The value
     * @param bool $exists Whether the key exists
     * @return void
     */
    private static function logAccess(string $operation, string $key, $value, bool $exists): void
    {
        // Check if logging is enabled (avoid infinite loop by not using Application::get)
        if (self::$logEnabled === null) {
            self::$logEnabled = isset($GLOBALS['Application']['app_log_enabled'])
                ? $GLOBALS['Application']['app_log_enabled']
                : false;
        }

        if (!self::$logEnabled) {
            return;
        }

        // Get log file path (avoid infinite loop by direct access)
        $logFile = isset($GLOBALS['Application']['app_log_file'])
            ? $GLOBALS['Application']['app_log_file']
            : sys_get_temp_dir() . '/application.log';

        $timestamp = date('Y-m-d H:i:s');
        $existsStr = $exists ? 'EXISTS' : 'DEFAULT';

        // Truncate value for logging
        $valueStr = is_scalar($value) ? (string)$value : gettype($value);
        if (strlen($valueStr) > 50) {
            $valueStr = substr($valueStr, 0, 50) . '...';
        }

        $logLine = sprintf(
            "[%s] APP %s [%s] key=%s value=%s (gets=%d, sets=%d)\n",
            $timestamp,
            $operation,
            $existsStr,
            $key,
            $valueStr,
            self::$getCount,
            self::$setCount
        );

        @file_put_contents($logFile, $logLine, FILE_APPEND | LOCK_EX);
    }

    /**
     * Get access statistics
     *
     * @return array Statistics with get/set counts
     */
    public static function getStats(): array
    {
        return [
            'gets' => self::$getCount,
            'sets' => self::$setCount,
            'total' => self::$getCount + self::$setCount,
        ];
    }

    /**
     * Reset access statistics
     *
     * @return void
     */
    public static function resetStats(): void
    {
        self::$getCount = 0;
        self::$setCount = 0;
    }

    /**
     * Enable or disable logging
     *
     * @param bool $enabled Whether to enable logging
     * @return void
     */
    public static function setLogEnabled(bool $enabled): void
    {
        self::$logEnabled = $enabled;
    }
}
