<?php
/**
 * Cookie.php - Cookie Access Manager
 *
 * Provides safe access to cookies with proper error handling and default values.
 * Replaces direct access to $_COOKIE array which can cause "Undefined array key" warnings.
 *
 * Usage:
 *   - Reading:  Cookie::get('CMAU', '')
 *   - Writing:  Cookie::set('CMAU', 'username', 3600*24*30)
 *   - Checking: Cookie::has('CMAU')
 *   - Deleting: Cookie::delete('CMAU')
 *
 * Generated by ASP to PHP Converter
 * https://github.com/anthropics/claude-code
 */

namespace App\Library;

class Cookie
{
    /**
     * Get a cookie value with optional default value
     *
     * @param string $name The cookie name
     * @param mixed $default Default value if cookie doesn't exist (default: '')
     * @return mixed The cookie value or default
     */
    public static function get(string $name, $default = '')
    {
        return $_COOKIE[$name] ?? $default;
    }

    /**
     * Set a cookie
     *
     * @param string $name The cookie name
     * @param string $value The cookie value
     * @param int $expire Expiration time in seconds from now (default: 0 = session cookie)
     * @param string $path The path on the server (default: '/')
     * @param string $domain The domain (default: '')
     * @param bool $secure Only send over HTTPS (default: false)
     * @param bool $httponly Only accessible via HTTP protocol (default: true)
     * @return bool True on success, false on failure
     */
    public static function set(
        string $name,
        ?string $value = '',
        int $expire = 0,
        string $path = '/',
        string $domain = '',
        bool $secure = false,
        bool $httponly = true
    ): bool {
        // If expire is relative (not 0), make it absolute
        if ($expire > 0) {
            $expire = time() + $expire;
        }

        $result = setcookie($name, $value ?? '', $expire, $path, $domain, $secure, $httponly);

        // Also update $_COOKIE array for immediate access in same request
        if ($result) {
            $_COOKIE[$name] = $value;
        }

        return $result;
    }

    /**
     * Check if a cookie exists
     *
     * @param string $name The cookie name
     * @return bool True if exists, false otherwise
     */
    public static function has(string $name): bool
    {
        return isset($_COOKIE[$name]);
    }

    /**
     * Delete a cookie
     *
     * @param string $name The cookie name
     * @param string $path The path on the server (default: '/')
     * @param string $domain The domain (default: '')
     * @return bool True on success, false on failure
     */
    public static function delete(string $name, string $path = '/', string $domain = ''): bool
    {
        // Set expiration time to past
        $result = setcookie($name, '', time() - 3600, $path, $domain);

        // Remove from $_COOKIE array
        if ($result) {
            unset($_COOKIE[$name]);
        }

        return $result;
    }

    /**
     * Get all cookies
     *
     * @return array All cookies
     */
    public static function all(): array
    {
        return $_COOKIE;
    }

    /**
     * Clear all cookies (client-side deletion on next request)
     *
     * Note: This only marks cookies for deletion. They will be removed
     * on the next request. Cannot clear cookies in current request.
     *
     * @param string $path The path on the server (default: '/')
     * @param string $domain The domain (default: '')
     * @return void
     */
    public static function clear(string $path = '/', string $domain = ''): void
    {
        foreach (array_keys($_COOKIE) as $name) {
            self::delete($name, $path, $domain);
        }
    }

    /**
     * Get cookie value with type casting
     *
     * @param string $name The cookie name
     * @param string $type The type to cast to ('int', 'float', 'bool', 'array')
     * @param mixed $default Default value if cookie doesn't exist
     * @return mixed The typed value or default
     */
    public static function getTyped(string $name, string $type, $default = null)
    {
        $value = self::get($name);

        if ($value === '') {
            return $default;
        }

        switch ($type) {
            case 'int':
                return (int) $value;
            case 'float':
                return (float) $value;
            case 'bool':
                return filter_var($value, FILTER_VALIDATE_BOOLEAN);
            case 'array':
                return json_decode($value, true) ?? $default;
            default:
                return $value;
        }
    }
}
